#!/bin/bash

# ========== PROJECT CONSTANTS ==========
PROJECT_NAME="ScriptedAliases"
PROJECT_ROOT_DIRECTORY="$HOME/.scripted_aliases"

# ========== PROJECT CONSTANTS ==========
PROJECT_ALIAS_REPOSITORY_LIST="$PROJECT_ROOT_DIRECTORY/scripts_directory.txt"
PROJECT_ALIAS_LIST="$PROJECT_ROOT_DIRECTORY/aliases.txt"
PROJECT_COMMANDS_LIST="$PROJECT_ROOT_DIRECTORY/commands.txt"

# ========== PROJECT TAGS ==========
SUDO_TAG="MS_SUDO"
ALIAS_TAG="MS_ALIAS"
IGNORE_TAG="MS_IGNORE"
SYSTEM_TAG="MS_SYSTEM"


